import { normalizeCarImagesFromDb } from "../../lib/carImages.js";
import type { TemplateCar } from "../../hub/models/TemplateCar.js";

export function serializeTemplateCar(c: TemplateCar): Record<string, unknown> {
  const imgs = normalizeCarImagesFromDb(c.images as unknown);
  return {
    id: c.id,
    title: c.title,
    brand: c.brand,
    model: c.model,
    year: c.year,
    price: Number(c.price),
    market_price: c.market_price != null ? Number(c.market_price) : null,
    fuel_type: c.fuel_type,
    transmission: c.transmission,
    km_driven: c.km_driven,
    location: c.location,
    images: imgs,
    image: imgs[0] ?? null,
    description: c.description,
    is_featured: c.is_featured,
    listing_status: c.listing_status,
    variant_name: c.variant_name ?? null,
    registration_year: c.registration_year ?? null,
    registration_month: c.registration_month ?? null,
    owner_count: c.owner_count ?? null,
    color: c.color ?? null,
    body_type: c.body_type ?? null,
    rto_city: c.rto_city ?? null,
    engine_cc: c.engine_cc ?? null,
    power_bhp: c.power_bhp != null ? Number(c.power_bhp) : null,
    torque_nm: c.torque_nm != null ? Number(c.torque_nm) : null,
    top_speed_kmph: c.top_speed_kmph ?? null,
    accel_0_100_sec: c.accel_0_100_sec != null ? Number(c.accel_0_100_sec) : null,
    drivetrain: c.drivetrain ?? null,
    seating_capacity: c.seating_capacity ?? null,
    boot_space_l: c.boot_space_l ?? null,
    battery_kwh: c.battery_kwh != null ? Number(c.battery_kwh) : null,
    range_km: c.range_km ?? null,
    charging_time_ac: c.charging_time_ac ?? null,
    charging_time_dc: c.charging_time_dc ?? null,
    insurance_valid_till: c.insurance_valid_till ?? null,
    warranty_info: c.warranty_info ?? null,
    service_history: c.service_history ?? null,
    sunroof: Boolean(c.sunroof),
    alloy_wheels: Boolean(c.alloy_wheels),
    led_headlamps: Boolean(c.led_headlamps),
    fog_lamps: Boolean(c.fog_lamps),
    rear_camera: Boolean(c.rear_camera),
    parking_sensors: Boolean(c.parking_sensors),
    ventilated_seats: Boolean(c.ventilated_seats),
    leather_seats: Boolean(c.leather_seats),
    ambient_lighting: Boolean(c.ambient_lighting),
    digital_cluster: Boolean(c.digital_cluster),
    airbags_count: c.airbags_count ?? null,
    abs: Boolean(c.abs),
    esc: Boolean(c.esc),
    tpms: Boolean(c.tpms),
    adas: Boolean(c.adas),
    android_auto: Boolean(c.android_auto),
    apple_carplay: Boolean(c.apple_carplay),
    wireless_charging: Boolean(c.wireless_charging),
    cruise_control: Boolean(c.cruise_control),
    emi_note: c.emi_note ?? null,
    createdAt: c.createdAt,
    updatedAt: c.updatedAt,
  };
}
